language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

install: 
  - pip install django
  - pip install south
  - pip install coveralls
  - pip install selenium

before_script:
  - cd src/

script:
  - coverage run --rcfile=../.coveragerc --source='.' manage.py test --pattern=tests_unit.py

after_success:
  - coveralls

notifications:
  email:
    recipients:
      - T.O.B.B.E@web.de
      - andreashaberl@gmx.net
      - tobiasseber@t-online.de
    on_success: always
    on_failure: always
