language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

install: 
  - pip install django
  - pip install south
  - pip install coveralls

before_script:
  - cd src/

script:
  - coverage run --source=moscowdjango,meetup manage.py test

after_success:
  - coveralls
