language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"

install: 
  - pip install django
  - pip install south
  - pip install coveralls
  - pip install selenium
  - npm install phantomjs

before_script:
  - cd src/
  - python3 manage.py runserver

script:
  - coverage run --rcfile=../.coveragerc --source='.' manage.py test 


after_success:
  - coveralls

notifications:
  email:
    recipients:
      - T.O.B.B.E@web.de
      - andreashaberl@gmx.net
      - tobiasseber@t-online.de
    on_success: always
    on_failure: always
