# used language
language: python
# versions to run
python:
  - "3.4"
# command to install dependencies
install: 
  - pip install django
  - pip install south
# command to run tests
before_script:
  - cd src/
  - python src/manage.py syncdb

script:
  - python src/manage.py test
