# used language
language: python
# versions to run
python:
  - "3.2"
  - "3.3"
  - "3.4"
# command to install dependencies
install: 
  - pip install django
  - pip install south
# command to run tests
before_script:
  - python manage.py syncdb

script:
  - python manage.py test
